plugins:
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - Draft.md
  - Draft_EN.md
  - Ideensammlung.md
  - Vorgeschichte.md

theme: jekyll-theme-tactile
